apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-05-12T15:12:17Z"
  generation: 5
  labels:
    app: eureka
  name: eureka
  namespace: default
  resourceVersion: "2708768"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/eureka
  uid: 0beec83b-5e11-4dfb-805d-c79a967bfb13
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: eureka
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: eureka
    spec:
      containers:
      - image: energygrids63d/eureka-server:latest
        imagePullPolicy: Always
        name: eureka-server-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-05-19T08:55:10Z"
    lastUpdateTime: "2020-05-19T08:55:10Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-05-12T15:12:17Z"
    lastUpdateTime: "2020-05-19T08:55:10Z"
    message: ReplicaSet "eureka-6b56f7d5c4" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 5
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-05-13T07:56:16Z"
  labels:
    app: eureka
  name: eureka-service
  namespace: default
  resourceVersion: "304624"
  selfLink: /api/v1/namespaces/default/services/eureka-service
  uid: ed2717b0-3eec-4731-bcb0-3a9d8b5bb6cd
spec:
  clusterIP: 10.93.8.99
  ports:
  - port: 8761
    protocol: TCP
    targetPort: 8761
  selector:
    app: eureka
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
